"""Paridade com `apps/cockpit/lib/spike/corrida-em-voo.test.ts` — mesmos
fixtures (cópia de JSONL real da frota, extraídos em 10/08), pra `_jsonl_lifecycle`
e `derive_lifecycle_from_event` não divergirem da régua do TS de novo."""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from orchestrator.lifecycle_ruido import eh_ruido_de_lifecycle

CAVEAT_DO_CLEAR = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands. DO NOT respond to these messages or "
    "otherwise consider them in your response unless the user explicitly "
    "asks you to.</local-command-caveat>"
)
COMANDO_LOCAL = (
    "<command-name>/compact</command-name>\n            "
    "<command-message>compact</command-message>\n            "
    "<command-args></command-args>"
)
RENAME_VIA_API = (
    '<system-reminder>\nThe user named this session "Maestro". This may '
    "indicate the session's focus or intent.\n</system-reminder>"
)
LEMBRETE = "<system-reminder>\nO teto de contexto é 30%.\n</system-reminder>"
RENAME_DIGITADO = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands.</local-command-caveat>\n"
    "<command-name>/rename</command-name>\n"
    "<command-message>rename</command-message>\n"
    "<command-args>Maestro</command-args>\n"
    "<local-command-stdout>Session renamed to: Maestro</local-command-stdout>\n"
    '<system-reminder>\nThe user named this session "Maestro".\n</system-reminder>'
)


@pytest.mark.parametrize(
    "texto",
    [CAVEAT_DO_CLEAR, COMANDO_LOCAL, RENAME_VIA_API, LEMBRETE, RENAME_DIGITADO],
)
def test_comando_local_e_reminder_sao_ruido(texto: str) -> None:
    assert eh_ruido_de_lifecycle(texto) is True


@pytest.mark.parametrize(
    "texto",
    [
        "arruma isso aí",
        "/rename Maestro",  # texto digitado cru, sem o wrapper do CC — é fala normal
        LEMBRETE + " e mais uma pergunta",  # reminder não isolado é conversa, não ruído
    ],
)
def test_fala_de_verdade_nao_e_ruido(texto: str) -> None:
    assert eh_ruido_de_lifecycle(texto) is False
