import assert from 'node:assert/strict';
import { test } from 'node:test';

import type { TaskEvent } from '@grupo_borges/cockpit-core/cockpit-types';

import { activityFromTaskEvent } from './frota-activity.ts';

// Mesmos fixtures de `apps/cockpit/lib/spike/corrida-em-voo.test.ts` — o card
// do fleet lê o mesmo tipo de payload cru que o watcher grava em `task_events`
// (`isSidechain` camelCase, não `is_sidechain`), então o formato do payload
// aqui é o do JSONL bruto, não o canônico do `/messages/stream`.
const CAVEAT_DO_CLEAR =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>';
const RENAME_VIA_API =
  '<system-reminder>\nThe user named this session "Maestro". This may indicate the session\'s focus or intent.\n</system-reminder>';

let proximoId = 0;

function eventoUser(content: unknown, extra: Record<string, unknown> = {}): TaskEvent {
  proximoId += 1;
  return {
    id: proximoId,
    task_id: null,
    agent_slug: 'maestro',
    instance_id: null,
    kind: 'jsonl:user',
    payload: { message: { role: 'user', content }, ...extra },
    created_at: 0,
  };
}

test('/rename via boot (system-reminder puro) não acende', () => {
  assert.equal(activityFromTaskEvent(eventoUser(RENAME_VIA_API)), null);
});

test('/clear digitado (caveat) não acende', () => {
  assert.equal(activityFromTaskEvent(eventoUser(CAVEAT_DO_CLEAR)), null);
});

test('fala de verdade continua acendendo trabalhando', () => {
  assert.equal(
    activityFromTaskEvent(eventoUser([{ type: 'text', text: 'arruma isso aí' }])),
    'trabalhando',
  );
});

test('resultado de ferramenta continua acendendo trabalhando', () => {
  assert.equal(
    activityFromTaskEvent(
      eventoUser([{ type: 'tool_result', tool_use_id: 'tu-1', content: 'ok' }]),
    ),
    'trabalhando',
  );
});

test('payload sem message reconhecível cai no fallback pessimista', () => {
  const evento: TaskEvent = {
    id: 999,
    task_id: null,
    agent_slug: 'maestro',
    instance_id: null,
    kind: 'jsonl:user',
    payload: {},
    created_at: 0,
  };
  assert.equal(activityFromTaskEvent(evento), 'trabalhando');
});

test('assistente com end_turn desliga', () => {
  const evento: TaskEvent = {
    id: 1000,
    task_id: null,
    agent_slug: 'maestro',
    instance_id: null,
    kind: 'jsonl:assistant',
    payload: { message: { role: 'assistant', content: 'pronto', stop_reason: 'end_turn' } },
    created_at: 0,
  };
  assert.equal(activityFromTaskEvent(evento), 'ocioso');
});
