import assert from 'node:assert/strict';
import { test } from 'node:test';

import type { MessagePayload } from '@grupo_borges/cockpit-core/messages-types';

import { corridaEmVoo } from './corrida-em-voo.ts';

// Os textos abaixo são CÓPIA de JSONL real da frota, extraídos em 10/08 da
// varredura de `~/.claude/projects/**/*.jsonl` (126 mil mensagens). Não são
// payload imaginado: é exatamente o que o Claude Code grava, incluindo a
// indentação do bloco de comando.
const CAVEAT_DO_CLEAR =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>';
const COMANDO_LOCAL =
  '<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>';
const INTERRUPCAO = '[Request interrupted by user]';
const LEMBRETE = '<system-reminder>\nO teto de contexto é 30%.\n</system-reminder>';

let proximoId = 0;

function mensagem(role: string, content: unknown, stopReason?: unknown): MessagePayload {
  proximoId += 1;
  return {
    id: proximoId,
    kind: role,
    uuid: `cv-${proximoId}`,
    parent_uuid: null,
    is_sidechain: false,
    user_type: 'external',
    timestamp: '2026-08-10T12:00:00.000Z',
    created_at: 0,
    message: stopReason === undefined
      ? { role, content }
      : { role, content, stop_reason: stopReason },
  } as unknown as MessagePayload;
}

const falaDoRica = (texto: string) => mensagem('user', [{ type: 'text', text: texto }]);
const resultado = () =>
  mensagem('user', [{ type: 'tool_result', tool_use_id: 'tu-1', content: 'ok' }]);

/* -------------------------------------------------------------------------- */
/* O que LIGA — trabalho de verdade começando                                  */
/* -------------------------------------------------------------------------- */

test('fala do Rica liga a corrida', () => {
  assert.equal(corridaEmVoo(false, [falaDoRica('arruma isso aí')]), true);
});

test('resultado de ferramenta mantém a corrida de pé', () => {
  assert.equal(corridaEmVoo(true, [resultado()]), true);
  // Sem a fala que abriu o turno no lote (replay parcial), o resultado sozinho
  // ainda é prova de que o agente está trabalhando.
  assert.equal(corridaEmVoo(false, [resultado()]), true);
});

test('assistente com tool_use segue em voo, e sem stop_reason também', () => {
  assert.equal(corridaEmVoo(true, [mensagem('assistant', 'chamando', 'tool_use')]), true);
  assert.equal(corridaEmVoo(true, [mensagem('assistant', 'parcial', null)]), true);
});

/* -------------------------------------------------------------------------- */
/* O que NÃO MEXE — mensagem que existe no log mas não é turno                 */
/* -------------------------------------------------------------------------- */

test('o caveat do /clear NÃO liga a corrida — era o "Pensando" eterno', () => {
  assert.equal(corridaEmVoo(false, [falaDoRica(CAVEAT_DO_CLEAR)]), false);
});

test('o bloco <command-name> de um comando local NÃO liga a corrida', () => {
  assert.equal(corridaEmVoo(false, [falaDoRica(COMANDO_LOCAL)]), false);
});

test('system-reminder NÃO liga a corrida', () => {
  assert.equal(corridaEmVoo(false, [falaDoRica(LEMBRETE)]), false);
});

test('mensagem neutra também não DESLIGA corrida legítima', () => {
  assert.equal(corridaEmVoo(true, [falaDoRica(LEMBRETE)]), true);
  assert.equal(corridaEmVoo(true, [falaDoRica(COMANDO_LOCAL)]), true);
});

/* -------------------------------------------------------------------------- */
/* O que DESLIGA — o turno acabou                                              */
/* -------------------------------------------------------------------------- */

test('assistente com end_turn desliga', () => {
  assert.equal(corridaEmVoo(true, [mensagem('assistant', 'pronto', 'end_turn')]), false);
});

test('fim que não é end_turn também desliga — stop_sequence, max_tokens', () => {
  assert.equal(corridaEmVoo(true, [mensagem('assistant', 'cortado', 'stop_sequence')]), false);
  assert.equal(corridaEmVoo(true, [mensagem('assistant', 'cortado', 'max_tokens')]), false);
});

test('ESC do Rica desliga — o turno foi abortado e nenhum end_turn virá', () => {
  assert.equal(corridaEmVoo(true, [falaDoRica(INTERRUPCAO)]), false);
});

/* -------------------------------------------------------------------------- */
/* Ordem e vazio                                                               */
/* -------------------------------------------------------------------------- */

test('subagente entregando não apaga a corrida de quem o chamou', () => {
  const doSubagente = mensagem('assistant', 'terminei', 'end_turn');
  (doSubagente as { is_sidechain: boolean }).is_sidechain = true;
  assert.equal(corridaEmVoo(true, [doSubagente]), true);
});

test('lote vazio preserva o estado anterior', () => {
  assert.equal(corridaEmVoo(true, []), true);
  assert.equal(corridaEmVoo(false, []), false);
});

test('quem manda é a ÚLTIMA mensagem que teve efeito', () => {
  const lote = [
    falaDoRica('vai'),
    mensagem('assistant', 'ok', 'end_turn'),
    falaDoRica(CAVEAT_DO_CLEAR),
  ];
  // O /clear depois do fim do turno não ressuscita o "Pensando".
  assert.equal(corridaEmVoo(false, lote), false);
});
