// Rodar: `node --test tests/local-command-wrapper.test.ts` (Node 22.22+).
//
// DS-65 F5-4 — fixtures cobrindo cada tag whitelist, mix concatenado, e os
// 2 cenários que NÃO podem disparar: texto livre puro e tag inline em texto
// real. Falso-positivo aqui esconde bubble legítima do user.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { looksLikeLocalCommandWrapper } from '../lib/local-command-wrapper.ts';

const POSITIVE: Array<{ name: string; raw: string }> = [
  {
    name: 'command-name isolado',
    raw: '<command-name>/model</command-name>',
  },
  {
    name: 'command-message isolado',
    raw: '<command-message>model</command-message>',
  },
  {
    name: 'command-args vazio',
    raw: '<command-args></command-args>',
  },
  {
    name: 'local-command-stdout multilinha',
    raw: '<local-command-stdout>Set model to opus.\nReady.</local-command-stdout>',
  },
  {
    name: 'local-command-caveat com prosa',
    raw: '<local-command-caveat>Caveat: messages generated by local commands. DO NOT respond.</local-command-caveat>',
  },
  {
    name: 'system-reminder isolado',
    raw: '<system-reminder>Some reminder text.</system-reminder>',
  },
  {
    name: 'sequência slash command típica (5 tags concatenadas)',
    raw: [
      '<command-name>/reload-plugins</command-name>',
      '<command-message>reload-plugins</command-message>',
      '<command-args></command-args>',
      '<local-command-stdout>Reloaded 2 plugins.</local-command-stdout>',
      '<local-command-caveat>Caveat: ...</local-command-caveat>',
    ].join('\n'),
  },
  {
    name: 'wrappers com whitespace entre',
    raw: '   <command-name>/clear</command-name>\n\n  <command-message>clear</command-message>   ',
  },
  {
    name: 'system-reminder + slash command misturados',
    raw: '<system-reminder>note</system-reminder>\n<command-name>/model</command-name>',
  },
];

const NEGATIVE: Array<{ name: string; raw: string }> = [
  {
    name: 'texto puro do user',
    raw: 'oi daniel, como você está?',
  },
  {
    name: 'texto + tag inline (proteção falso-positivo)',
    raw: 'olha esse XML que apareceu: <command-name>/model</command-name> — esquisito',
  },
  {
    name: 'tag whitelist + texto livre depois',
    raw: '<command-name>/model</command-name>\nopina sobre isso aqui',
  },
  {
    name: 'tag não whitelist isolada — channel envelope',
    raw: '<channel source="telegram" chat_id="123"><body>oi</body></channel>',
  },
  {
    name: 'tag não whitelist — task-notification',
    raw: '<task-notification><task-id>abc</task-id><status>completed</status></task-notification>',
  },
  {
    name: 'string vazia',
    raw: '',
  },
  {
    name: 'só whitespace',
    raw: '   \n\t  ',
  },
  {
    name: 'tag mal-formada (sem fechamento)',
    raw: '<command-name>/model',
  },
  {
    name: 'tag fechada com nome diferente',
    raw: '<command-name>x</command-args>',
  },
  {
    name: 'wrapper com atributo (não casa — bubble fica visível por conservadorismo)',
    raw: '<system-reminder priority="high">x</system-reminder>',
  },
];

const POSITIVE_WHITESPACE: Array<{ name: string; raw: string }> = [
  {
    name: 'tag com whitespace antes do >',
    raw: '<command-name >/clear</command-name >',
  },
];

test('looksLikeLocalCommandWrapper — positivos (esconder)', () => {
  const failed: string[] = [];
  for (const fx of POSITIVE) {
    if (!looksLikeLocalCommandWrapper(fx.raw)) {
      failed.push(`${fx.name}: esperado true, got false`);
    }
  }
  assert.equal(failed.length, 0, `\n${failed.join('\n')}`);
});

test('looksLikeLocalCommandWrapper — negativos (manter bubble)', () => {
  const failed: string[] = [];
  for (const fx of NEGATIVE) {
    if (looksLikeLocalCommandWrapper(fx.raw)) {
      failed.push(`${fx.name}: esperado false, got true`);
    }
  }
  assert.equal(failed.length, 0, `\n${failed.join('\n')}`);
});

test('looksLikeLocalCommandWrapper — tolera whitespace na tag', () => {
  const failed: string[] = [];
  for (const fx of POSITIVE_WHITESPACE) {
    if (!looksLikeLocalCommandWrapper(fx.raw)) {
      failed.push(`${fx.name}: esperado true, got false`);
    }
  }
  assert.equal(failed.length, 0, `\n${failed.join('\n')}`);
});
